services:
  traefik:
    image: traefik:v2.9.4
    command:
      - --accesslog=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedByDefault=false
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
      - --providers.docker.network=${XEBRO_PROJECT_NAME}
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - "${XEBRO_MODULES_DIR}/traefik/certs:/etc/traefik/certs"
      - "${XEBRO_MODULES_DIR}/traefik/config.yaml:/etc/traefik/dynamic_conf/config.yaml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  default:
    external: true
    name: ${XEBRO_PROJECT_NAME}